<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>WXPlayer</AssemblyName><Version>1.4.0</Version><RuntimeIdentifier>win-x64</RuntimeIdentifier></PropertyGroup><ItemGroup><ProjectReference Include="../../src/WXPlayer.Core/WXPlayer.Core.csproj"/></ItemGroup></Project>

